# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rY0Wly7iLW-S2rQqX-0p3iXonOeREaAn
"""

import numpy as np
from scipy.integrate import simpson # Changed from simps to simpson
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

class MobiusStrip:
    def __init__(self, R=1.0, w=0.2, n=100):
        self.R = R
        self.w = w
        self.n = n
        self.u, self.v = np.meshgrid(np.linspace(0, 2 * np.pi, n), np.linspace(-w / 2, w / 2, n))
        self.x, self.y, self.z = self._generate_points()

    def _generate_points(self):
        u2 = self.u / 2
        x = (self.R + self.v * np.cos(u2)) * np.cos(self.u)
        y = (self.R + self.v * np.cos(u2)) * np.sin(self.u)
        z = self.v * np.sin(u2)
        return x, y, z

    def surface_area(self):
        dx_du = np.gradient(self.x, axis=0)
        dy_dv = np.gradient(self.y, axis=1)
        dz_du = np.gradient(self.z, axis=0)
        dx_dv = np.gradient(self.x, axis=1)
        dy_du = np.gradient(self.y, axis=0)
        dz_dv = np.gradient(self.z, axis=1)

        cross_prod = np.cross(
            np.stack([dx_du, dy_du, dz_du], axis=-1),
            np.stack([dx_dv, dy_dv, dz_dv], axis=-1)
        )
        area_density = np.linalg.norm(cross_prod, axis=2)
        # Changed simps to simpson and adjusted arguments for 2D integration
        return simpson(simpson(area_density, self.v[0]), self.u[:,0])

    def edge_length(self):
        # Sample along edge v = ±w/2
        edge_u = np.linspace(0, 2 * np.pi, self.n)
        v_edge = np.full_like(edge_u, self.w / 2)
        u2 = edge_u / 2

        x = (self.R + v_edge * np.cos(u2)) * np.cos(edge_u)
        y = (self.R + v_edge * np.cos(u2)) * np.sin(edge_u)
        z = v_edge * np.sin(u2)

        points = np.stack([x, y, z], axis=1)
        diffs = np.diff(points, axis=0)
        distances = np.linalg.norm(diffs, axis=1)
        return np.sum(distances)

    def plot(self):
        fig = plt.figure()
        ax = fig.add_subplot(111, projection='3d')
        ax.plot_surface(self.x, self.y, self.z, rstride=1, cstride=1, cmap='viridis', edgecolor='none')
        ax.set_title('Möbius Strip')
        plt.show()


if __name__ == "__main__":
    strip = MobiusStrip(R=1.0, w=0.2, n=200)
    print("Surface Area:", strip.surface_area())
    print("Edge Length:", strip.edge_length())
    strip.plot()